export type Game = {
  id: string;
  developer_id: string;
  title: string;
  slug: string;
  description: string | null;
  thumbnail_url: string | null;
  game_url: string | null;
  manual_url: string | null;
  status: string | null;
  version: string | null;
  genre: string | null;
  available_modes: string[] | null;
  created_at: string | null;
  updated_at: string | null;
  rating: number | null;
  players: number | null;
  edad_minima: number | null;
  price: number | null;
};